services:
  x-postgres-common: &postgres-common
    image: postgres:16.1

  postgres:
    <<: *postgres-common
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

  user-db:
    <<: *postgres-common
    container_name: user-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      retries: 5

  request-db:
    <<: *postgres-common
    container_name: request-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: request
      POSTGRES_USER: request
      POSTGRES_PASSWORD: request
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U request" ]
      interval: 5s
      retries: 5

  comment-db:
    <<: *postgres-common
    container_name: comment-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: comment
      POSTGRES_USER: comment
      POSTGRES_PASSWORD: comment
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U comment" ]
      interval: 5s
      retries: 5

  stats-db:
    <<: *postgres-common
    container_name: postgres-ewm-stats-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats"]
      interval: 5s
      retries: 5