spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user_service_admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - PrefixPath=/
        - id: event_service_compilations
          uri: lb://event-service
          predicates:
            - Path=/compilations/**
          filters:
            - PrefixPath=/
        - id: event_service_admin_compilations
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**
          filters:
            - PrefixPath=/
        - id: event_service_events
          uri: lb://event-service
          predicates:
            - Path=/events/**, /users/{userId:\d+}/events, /users/{userId:\d+}/events/{eventId:\d+}, /internal/events/**
          filters:
            - PrefixPath=/
        - id: event_service_admin_events
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**
          filters:
            - PrefixPath=/
        - id: event_service_categories
          uri: lb://event-service
          predicates:
            - Path=/categories/**
          filters:
            - PrefixPath=/
        - id: event_service_admin_categories
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**
          filters:
            - PrefixPath=/
        - id: event_service_comments
          uri: lb://event-service
          predicates:
            - Path=/comments/**
          filters:
            - PrefixPath=/
        - id: event_service_admin_comments
          uri: lb://event-service
          predicates:
            - Path=/admin/comments/**
          filters:
            - PrefixPath=/
        - id: request_service_users
          uri: lb://request-service
          predicates:
            - Path=/users/{userId:\d+}/requests, /users/{userId:\d+}/requests/**
          filters:
            - PrefixPath=/
        - id: request_service_events
          uri: lb://request-service
          predicates:
            - Path=/users/{userId:\d+}/events/{eventId:\d+}/requests, /internal/requests/**
          filters:
            - PrefixPath=/
      discovery:
        locator:
          enabled: true
      metrics:
        enabled: true
server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
      access: read-only
  endpoints:
    web:
      exposure:
        include: gateway