-- ============================================================================
-- СХЕМА БАЗЫ ДАННЫХ EXPLORE WITH ME
-- ============================================================================

-- Удаление таблиц в правильном порядке (сначала зависимые, потом родительские)
DROP TABLE IF EXISTS compilation_events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================================================
-- ПОЛЬЗОВАТЕЛИ
-- ============================================================================
CREATE TABLE IF NOT EXISTS users (
                                     id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name   VARCHAR(250) NOT NULL,
    email  VARCHAR(254) NOT NULL UNIQUE
    );

-- ============================================================================
-- КАТЕГОРИИ
-- ============================================================================
CREATE TABLE IF NOT EXISTS categories (
                                          id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(64) NOT NULL UNIQUE
    );

-- ============================================================================
-- СОБЫТИЯ
-- ============================================================================
CREATE TABLE IF NOT EXISTS events (
                                      id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      annotation         VARCHAR(2000) NOT NULL,
    category_id        BIGINT NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id       BIGINT NOT NULL,
    lat                REAL NOT NULL,
    lon                REAL NOT NULL,
    paid               BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit  INTEGER NOT NULL DEFAULT 0,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    state              VARCHAR(20) NOT NULL,
    title              VARCHAR(120) NOT NULL,
    comments_enabled   BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_event_to_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_event_to_user FOREIGN KEY (initiator_id) REFERENCES users(id)
    );

-- Индексы для событий
CREATE INDEX idx_events_category_id ON events(category_id);
CREATE INDEX idx_events_initiator_id ON events(initiator_id);
CREATE INDEX idx_events_event_date ON events(event_date);
CREATE INDEX idx_events_state ON events(state);

-- ============================================================================
-- КОММЕНТАРИИ
-- ============================================================================
CREATE TABLE IF NOT EXISTS comments (
                                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text        VARCHAR(2000) NOT NULL,
    created_on  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_on  TIMESTAMP WITHOUT TIME ZONE,
    author_id   BIGINT NOT NULL,
    event_id    BIGINT NOT NULL,
    is_edited   BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_comment_to_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_to_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
    );

-- Индексы для комментариев
CREATE INDEX idx_comments_event_id ON comments(event_id);
CREATE INDEX idx_comments_author_id ON comments(author_id);
CREATE INDEX idx_comments_created_on ON comments(created_on);

-- ============================================================================
-- ЗАПРОСЫ НА УЧАСТИЕ
-- ============================================================================
CREATE TABLE IF NOT EXISTS requests (
                                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        event_id     BIGINT NOT NULL,
                                        requester_id BIGINT NOT NULL,
                                        status       VARCHAR(20) NOT NULL,

    CONSTRAINT fk_request_to_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_request_to_requester FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT uq_request_requester_event UNIQUE (requester_id, event_id)
    );

-- Индексы для запросов
CREATE INDEX idx_requests_event_id ON requests(event_id);
CREATE INDEX idx_requests_requester_id ON requests(requester_id);
CREATE INDEX idx_requests_status ON requests(status);

-- ============================================================================
-- ПОДБОРКИ
-- ============================================================================
CREATE TABLE IF NOT EXISTS compilations (
                                            id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            pinned BOOLEAN NOT NULL DEFAULT FALSE,
                                            title  VARCHAR(128) NOT NULL UNIQUE
    );

-- ============================================================================
-- СВЯЗЬ ПОДБОРОК И СОБЫТИЙ (многие ко многим)
-- ============================================================================
CREATE TABLE IF NOT EXISTS compilation_events (
                                                  compilation_id BIGINT NOT NULL,
                                                  event_id       BIGINT NOT NULL,

                                                  PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_ce_to_compilation FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    CONSTRAINT fk_ce_to_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
    );

-- Индексы для связей
CREATE INDEX idx_compilation_events_compilation_id ON compilation_events(compilation_id);
CREATE INDEX idx_compilation_events_event_id ON compilation_events(event_id);